name: helm_push

on:
  push:
    branches:
      - main
  #workflow_run:
    #workflows: ["helm_lint"]
    #types:
      #- completed

jobs:
  helm_push:
    uses: Ssases/reusable-workflows/.github/workflows/helm-process.yml@main
    with:
      helm_package: helm/surface
      version: 3656589
