name: Tag Manage

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  tag:
    uses: Ssases/reusable-workflows/.github/workflows/tag_manage_RW.yml@main
    
  tag_output:
     runs-on: ubuntu-latest 
     needs: tag 
     steps:
     
     - name: tag output
       run: |
          echo ${{ needs.tag.outputs.computed_tag_prod }}
         # echo ${{ needs.tag_manage.outputs.tag_version_dev }}
       
