name: Tag Manage

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  tag_manage:
    uses: Ssases/reusable-workflows/.github/workflows/tag_manage_RW.yml@main
    
  tag_output:
     runs-on: ubuntu-latest 
     needs: tag_manage 
     steps:
     
     - name: tag output
       run: echo ${{ needs.tag_manage.outputs.GIT_TAG }}
